name: FBNAFNet
model_type: ImageRestorationModel
scale: 1
num_gpu: 4
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: gopro-train
    type: Flow_Blur_dataset
    dataroot_gt: /workspace/FFTformer/datasets/gopro_train_flows.txt
    dataroot_lq: /workspace/FFTformer/datasets/gopro_train_flows.txt

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: gopro-test
    type: Flow_Blur_dataset
    dataroot_gt: /workspace/FFTformer/datasets/gopro_val_flows.txt
    dataroot_lq: /workspace/FFTformer/datasets/gopro_val_flows.txt
    io_backend:
      type: disk

# network structures
network_g:
  type: FBNAFNet
  width: 64
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]

# path
# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 5e-4
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 1000000
    eta_min: !!float 1e-7

  total_iter: 1000000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: true


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    # ssim:
    #   type: calculate_ssim
    #   crop_border: 0
    #   test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
