name: EFNet_C_pusedo_16_600k
model_type: ImageRestorationModel
scale: 1
num_gpu:  4
manual_seed: 10

datasets:
  train:
    name: gopro-train
    type: Flow_Blur_dataset_C
    dataroot_gt: /workspace/data/Gopro_my/train.txt
    dataroot_lq: /workspace/data/Gopro_my/train.txt

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: gopro-test
    type: Flow_Blur_dataset_C
    dataroot_gt: /workspace/data/Gopro_my/val.txt
    dataroot_lq: /workspace/data/Gopro_my/val.txt
    io_backend:
      type: disk


# network structures
network_g:
  type: EFNet
  wf: 64 
  fuse_before_downsample: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 600000
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 0.5
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    
    # ssim:
    #   type: calculate_ssim
    #   crop_border: 0
    #   test_y_channel: false   

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500